config/routes.rb
MailchimpCoupons::Application.routes.draw do
  match '/auth/:provider/callback', :to => 'sessions#show'
  match '/logout', :to => "sessions#destroy", :as => "logout"

  resources :coupons do
    post '/consume', to: 'coupons#consume', as: 'consume_coupon', on: :member
    post '/subscribe', to: 'coupons#subscribe', as: 'subscribe', on: :member
    post '/send_to_consumed', to: 'coupons#send_to_consumed', as: "send_to_consumed", on: :member
    post '/send_to_unconsumed', to: 'coupons#send_to_unconsumed', as: "send_to_unconsumed", on: :member
  end

  get  '/dashboard', to: 'home#show'
  root to: 'home#index'

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :user
  before_create :create_merge_var
  before_destroy :destroy_merge_var
  before_update :update_merge_var_name

  def create_merge_var
    self.tag = "COUPON#{user.next_coupon_num}"
    user.api.listMergeVarAdd(id: list_id,tag: self.tag, name: name, options: {public: false,show:false, default_value: ''})
  end

  def destroy_merge_var
    user.api.listMergeVarDel(id: list_id, tag: tag)
  end
  
  def update
    user.api.listMergeVarUpdate(id: list_id, tag: tag, options: {name: self.name}) if name_changed?
  end
  
  def create_consumed_campaign
    campaign_url_for(user.api.campaignCreate(default_campaign_options.merge({
        segment_opts: {match: "all", conditions: [{field: tag, op: "eq", value: "consumed"}]}})))
  end
  
  def create_unconsumed_campaign
    cid = user.api.campaignCreate(default_campaign_options.merge({
      segment_opts: {match: "all", conditions: [{field: tag, op: "ne", value: "consumed"}]}}))
    campaign_url_for(cid)
  end
  
  def consume(email)
    response = user.api.listMemberInfo(id: list_id, email_address: email)
    result =  {response: "NotSubscribed", email: email} if not_subscribed?(response)
    result =  consume_and_respond(email) if subscribed_and_not_consumed?(response)
    result = {response: "AlreadyConsumed", email: email} if subscribed_and_consumed?(response)
    result
  end

  private
    def subscribed_and_not_consumed?(response)
      response['success'] == 1 and response['data'][0]['merges'][tag] != "consumed"
    end

    def subscribed_and_consumed?(response)
      response['success'] == 1 and response['data'][0]['merges'][tag] == "consumed"
    end

    def not_subscribed?(response)
      response['errors'] == 1
    end
    
    def consume_and_respond(email)
      user.api.listUpdateMember(id: list_id, email_address: email, merge_vars: {"#{tag}" => 'consumed'})
      {response: "Consumed", email: email}
    end
    
    def default_campaign_options
      list = user.api.lists(filters: {list_id: list_id})['data'][0]
      {type: 'regular', options: {
            list_id: list_id, title: name, subject: list['default_subject'],
            from_name: list['default_from_name'], from_email: list['default_from_email'], to_name: name},
          content: {html_HEADER:"", html_MAIN:"", html_SIDECOLUMN:"", html_FOOTER:"", text: name}}
    end
    
    def campaign_url_for(cid)
      return cid if(cid['error'])
      web_id = user.api.campaigns(filters: {campaign_id: cid})['data'][0]['web_id']
      "https://#{user.api.api_key.split("-")[1]}.admin.mailchimp.com/campaigns/wizard/recipients?id=#{web_id}"
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :coupons

  def next_coupon_num
    new_count = coupons_count + 1
    update_attribute(:coupons_count, new_count)
    new_count
  end

  def api
    @api ||= Mailchimp::API.new(apikey)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def logged_in?
    not current_user.nil?
  end
  def current_user
    @current_user ||= session[:user] ? User.find(session[:user]) : nil
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_filter :logged_in?
  # GET /coupons
  # GET /coupons.json
  def index
    redirect_to controller: :home, action: :index unless logged_in?
    @coupons = current_user.coupons
    @lists = current_user.api.lists['data']
    logger.info @lists.inspect
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coupons }
    end
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
    @coupon = current_user.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coupon }
    end
  end

  # GET /coupons/new
  # GET /coupons/new.json
  def new
    @coupon = current_user.coupons.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coupon }
    end
  end

  # GET /coupons/1/edit
  def edit
    @coupon = current_user.coupons.find(params[:id])
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = current_user.coupons.create(params[:coupon])

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to @coupon, notice: 'Coupon was successfully created.' }
        format.json { render json: @coupon, status: :created, location: @coupon }
      else
        format.html { render action: "new" }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /coupons/1
  # PUT /coupons/1.json
  def update
    @coupon = current_user.coupons.find(params[:id])

    respond_to do |format|
      if @coupon.update_attributes(params[:coupon])
        format.html { redirect_to @coupon, notice: 'Coupon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon = current_user.coupons.find(params[:id])
    @coupon.destroy

    respond_to do |format|
      format.html { redirect_to coupons_url }
      format.json { head :no_content }
    end
  end
  
  # POST /coupons/1/consume
  def consume
    @coupon = current_user.coupons.find(params[:id])
    render json: @coupon.consume(params[:email])
  end

  def subscribe
    res = current_user.api.listSubscribe(id: params[:list_id],email_address: params[:email],
                                                merge_vars: {"OPTIN-IP" => request.remote_ip, "OPTIN-TIME" => Time.now})
    render json:  res
  end

  def send_to_consumed
    @coupon = current_user.coupons.find(params[:id])
    render json: {result: @coupon.create_consumed_campaign}
  end
  
  def send_to_unconsumed
    @coupon = current_user.coupons.find(params[:id])
    render json: {result: @coupon.create_unconsumed_campaign}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to action: :show if logged_in?
  end

  def show
    redirect_to action: :index and return unless logged_in?
    redirect_to controller: :coupons, action: :index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
    @auth = request.env['omniauth.auth']
    apikey = "#{@auth['credentials']['token']}-#{@auth['extra']['metadata']['dc']}"
    u = User.find_or_create_by_user_id(@auth['info']['uid'])
    u.update_attributes(apikey: apikey, username: @auth['extra']['raw_info']['username'])
    session[:user] = u.id
    redirect_to root_url
  end
  def destroy
    reset_session
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/coupons/_form.html.erb
<%= form_for(@coupon) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% @coupon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :list_id %><br />
    <%= f.text_field :list_id %>
  </div>
  <div class="field">
    <%= f.label :merge_tag %><br />
    <%= f.text_field :merge_tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<div id="coupons"></div>
<script>
  MailchimpCoupons.Lists = <%= @lists.to_json.html_safe%>;
  window.router = new MailchimpCoupons.Routers.CouponsRouter({coupons: <%= @coupons.to_json.html_safe %>});
  Backbone.history.start();
</script>

app/views/coupons/new.html.erb
<h1>New coupon</h1>

<%= render 'form' %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @coupon.user_id %>
</p>

<p>
  <b>List:</b>
  <%= @coupon.list_id %>
</p>

<p>
  <b>Merge tag:</b>
  <%= @coupon.merge_tag %>
</p>


<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Mailchimp Coupons</title>

<%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


</head>
<body>
  
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Mailchimp Coupons", "/", :class => "brand" %>
        <ul class="nav">
          
        </ul>
        <div class="pull-right">
        <% if(session[:user])%>
  				<li><%=link_to "Logout", logout_path, class: "btn"%></li>
  			<% else %>
  				<li><%=link_to "Login", "/auth/mailchimp", class: "btn"%></li>
  			<% end %>
  			</div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <div style="display: none;" class="modal hide fade in confirmable-modal">
      <div class="modal-header">
        <h3 class="confirmable-header">Are you sure?</h3>
      </div>
      <div class="modal-body confirmable-body">
        <p>This is a default message.</p>
      </div>
      <div class="modal-footer">
        <a class="btn primary confirmable-confirmation"  href="#">Confirm</a>
        <a class="btn secondary confirmable-cancellation" href="#">Cancel</a>
      </div>
    </div>
</body>
</html>